export interface Quote {
  text: string;
  author: string;
}

/**
 * Curated quotes on habits, consistency, discipline and perseverance. One is shown per day
 * (see quote-of-the-day.ts). Edit freely — order doesn't matter; the daily pick is deterministic.
 */
export const quotes: Quote[] = [
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
  { text: "Success is the product of daily habits — not once-in-a-lifetime transformations.", author: "James Clear" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Habits are the compound interest of self-improvement.", author: "James Clear" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "If you get 1% better each day, you'll end up 37 times better by the end of the year.", author: "James Clear" },
  { text: "We first make our habits, and then our habits make us.", author: "John Dryden" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "The secret of your future is hidden in your daily routine.", author: "Mike Murdock" },
  { text: "Small disciplines repeated with consistency every day lead to great achievements.", author: "John C. Maxwell" },
  { text: "It's not what we do once in a while that shapes our lives, but what we do consistently.", author: "Tony Robbins" },
  { text: "Repetition is the mother of skill.", author: "Tony Robbins" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Success isn't always about greatness. It's about consistency.", author: "Dwayne Johnson" },
  { text: "You'll never change your life until you change something you do daily.", author: "John C. Maxwell" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Persistence guarantees that results are inevitable.", author: "Paramahansa Yogananda" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The chains of habit are too weak to be felt until they are too strong to be broken.", author: "Samuel Johnson" },
  { text: "First forget inspiration. Habit is more dependable.", author: "Octavia Butler" },
  { text: "Your habits will determine your future.", author: "Jack Canfield" },
  { text: "Nothing in the world can take the place of persistence.", author: "Calvin Coolidge" },
  { text: "What you do every day matters more than what you do once in a while.", author: "Gretchen Rubin" },
  { text: "Take care of the minutes and the hours will take care of themselves.", author: "Lord Chesterfield" },
  { text: "Habits change into character.", author: "Ovid" },
  { text: "Sow an action, reap a habit; sow a habit, reap a character.", author: "Stephen Covey" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Bill Phillips" },
  { text: "You will never always be motivated. You have to learn to be disciplined.", author: "Unknown" },
  { text: "The pain of discipline is far less than the pain of regret.", author: "Unknown" },
  { text: "How you do anything is how you do everything.", author: "T. Harv Eker" },
  { text: "Slow is smooth, and smooth is fast.", author: "Navy SEAL saying" },
  { text: "Ambition is the path to success. Persistence is the vehicle you arrive in.", author: "Bill Bradley" },
  { text: "Winners embrace hard work.", author: "Lou Holtz" },
  { text: "The only discipline that lasts is self-discipline.", author: "Bum Phillips" },
  { text: "We become what we repeatedly do.", author: "Sean Covey" },
  { text: "Consistency is the true foundation of trust — with others and with yourself.", author: "Roy T. Bennett" },
];
